### ISSUE TITLE
Short ids are only replacing the first '+' and first '/' characters.

### ISSUE THREAD

**Issue by derrickdominic** [TheHippo/mongodb-short-id#1]
I believe line 4 should be

``` javascript
shortID = shortID.replace(/-/g, '+').replace(/_/g, '/');
```

and line 11 should be

``` javascript
return buffer.toString('base64').replace(/\+/g, '-').replace(/\//g, '_');
```

**Comment by TheHippo** [comment]
[Link to the mentioned line](https://github.com/TheHippo/mongodb-short-id/blob/351c4d7d8084b6fec1fa27e477a6375240ed74c5/src/mongodb-short-id.js#L11)
